package com.sduduzog.slimlauncher.ui.compose.theme

import androidx.compose.ui.graphics.Color

// Material 3 color scheme
val md_theme_light_primary = Color(0xFF006B5A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF73F8DD)
val md_theme_light_onPrimaryContainer = Color(0xFF00201A)
val md_theme_light_secondary = Color(0xFF4A635D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E0)
val md_theme_light_onSecondaryContainer = Color(0xFF06201B)
val md_theme_light_tertiary = Color(0xFF426278)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC7E6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E31)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFA)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFDFA)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E0)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EF)
val md_theme_light_inverseSurface = Color(0xFF2E3130)
val md_theme_light_inversePrimary = Color(0xFF53DBC1)

val md_theme_dark_primary = Color(0xFF53DBC1)
val md_theme_dark_onPrimary = Color(0xFF00382E)
val md_theme_dark_primaryContainer = Color(0xFF005143)
val md_theme_dark_onPrimaryContainer = Color(0xFF73F8DD)
val md_theme_dark_secondary = Color(0xFFB1CCC5)
val md_theme_dark_onSecondary = Color(0xFF1C352F)
val md_theme_dark_secondaryContainer = Color(0xFF334B46)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E0)
val md_theme_dark_tertiary = Color(0xFFAACAE6)
val md_theme_dark_onTertiary = Color(0xFF0F3449)
val md_theme_dark_tertiaryContainer = Color(0xFF294A60)
val md_theme_dark_onTertiaryContainer = Color(0xFFC7E6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E1)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E1)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E1)
val md_theme_dark_inversePrimary = Color(0xFF006B5A)
